### ISSUE TITLE
Repasar datos incidencia Navarra

### ISSUE THREAD

**Issue by albertotb** [Komorebi-AI/modelling-week-2021#58]
En los datos de incidencia aparecen NC, que es el código de la provincia de Navarra y NA, que es el código de la CCAA de Navarra. Hay que tener cuidado con esto porque además, NC se usa en otras columnas como "No conocido". ¿Es posible que los datos de Navarra estén repetidos? Habría que repasar esto

Códigos ISO: https://es.wikipedia.org/wiki/ISO_3166-2:ES

**Comment by daniprec** [comment]
No tienen nada que ver:
![image](https://user-images.githubusercontent.com/34949631/121262736-e8c7aa80-c8b4-11eb-925e-fbdb02f29f10.png)

**Comment by albertotb** [comment]
Y cuáles son los buenos?

**Comment by albertotb** [comment]
El bug que había antes es que, con

```
na_values = ["NC"]
```

También se cambian "NA" por NA. La solución es poner `keep_default_na=False` y reemplazar a mano los "NC" de las columnas sexo y edad por NA.

El problema es que ahí tenemos datos de Navarra provincia (NC) y Navarra comunidad (NA), que no coinciden. Ahora mismo el script se queda con los NC porque es el código ISO que está en el fichero `/data/raw/CCAA.csv`. Para quedarse con los NA basta hacer replace de NC como NA (como estaba antes, pero que no estaba haciendo nada porque los NA se habían cambiado por NaN).

**Comment by daniprec** [comment]
La información de los datos se detalla en: https://cnecovid.isciii.es/covid19/resources/metadata_tecnica_ccaa_prov_res.pdf
Pone:
**provincia_iso**: Código ISO de la provincia de residencia. NC (no consta)
